name: lur1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - libgdal-jp2openjpeg
  - rasterio
  - geopandas
  - pyproj
  - shapely
  - fiona
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - joblib
  - pyyaml
  - jupyter
  - ipykernel
  - requests
  - pip
